# install python3 and pip
# $ sudo apt-get install python3 python3-pip
# force Python 3 if necessary
# $ export ANSIBLE_PYTHON_INTERPRETER=/usr/bin/python3
# $ pip3 install --user solidfire-sdk-python
# fix and refresh $PATH if necessary
# change vars if you want them hardcoded, and run
# in order to re-run the script, remove created volume 
#   (because you can't shrink it after it's been enlarged)

- name: Create new volume and change properties of existing volume
  hosts: localhost 
  connection: local
  gather_facts: no
  collections:
    - netapp.elementsw
    - ansible.builtin

  vars:
    elementsw_hostname: 192.168.1.34
    elementsw_username: admin
    elementsw_password: admin
    storage_tenant_account_id: 1
    volume_name: "just-use-powershell"

  tasks:
    - name: Create Volume
      na_elementsw_volume:
        hostname: "{{ elementsw_hostname }}"
        username: "{{ elementsw_username }}"
        password: "{{ elementsw_password }}"
        state: present
        name: "{{ volume_name }}"
        qos: {minIOPS: 100, maxIOPS: 200, burstIOPS: 300}
        account_id: "{{ storage_tenant_account_id }}"
        enable512e: True
        size: 2
        size_unit: gb
    - name: Modify Volume
      na_elementsw_volume:
        hostname: "{{ elementsw_hostname }}"
        username: "{{ elementsw_username }}"
        password: "{{ elementsw_password }}"
        state: present
        name: "{{ volume_name }}"
        qos: {minIOPS: 200, maxIOPS: 300, burstIOPS: 400}
        account_id: "{{ storage_tenant_account_id }}"
        enable512e: True
        size: 3
        size_unit: gb
